"""autogenerated by genpy from kobuki_msgs/CliffEvent.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CliffEvent(genpy.Message):
  _md5sum = "768947926ed252fd64a5711160ff3884"
  _type = "kobuki_msgs/CliffEvent"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Provides a cliff sensor event
# This message is generated whenever the robot approaches or moves away from a cliff

uint8 LEFT   = 0
uint8 CENTER = 1
uint8 RIGHT  = 2

uint8 FLOOR = 0
uint8 CLIFF = 1

uint8  state
uint8  sensor
uint16 bottom
"""
  # Pseudo-constants
  LEFT = 0
  CENTER = 1
  RIGHT = 2
  FLOOR = 0
  CLIFF = 1

  __slots__ = ['state','sensor','bottom']
  _slot_types = ['uint8','uint8','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,sensor,bottom

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CliffEvent, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = 0
      if self.sensor is None:
        self.sensor = 0
      if self.bottom is None:
        self.bottom = 0
    else:
      self.state = 0
      self.sensor = 0
      self.bottom = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2BH.pack(_x.state, _x.sensor, _x.bottom))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.state, _x.sensor, _x.bottom,) = _struct_2BH.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2BH.pack(_x.state, _x.sensor, _x.bottom))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.state, _x.sensor, _x.bottom,) = _struct_2BH.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2BH = struct.Struct("<2BH")
