"""autogenerated by genpy from kobuki_msgs/DigitalOutput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DigitalOutput(genpy.Message):
  _md5sum = "1e97cd7f196a0270516b506e8bf29ca2"
  _type = "kobuki_msgs/DigitalOutput"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Digital output - only four pins. 

# Array of values indices represent pins 0-3 respectively.
bool[4] values

# Set indices to true to set a pin, false to ignore.
bool[4] mask

"""
  __slots__ = ['values','mask']
  _slot_types = ['bool[4]','bool[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       values,mask

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DigitalOutput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.values is None:
        self.values = [False,False,False,False]
      if self.mask is None:
        self.mask = [False,False,False,False]
    else:
      self.values = [False,False,False,False]
      self.mask = [False,False,False,False]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_4B.pack(*self.values))
      buff.write(_struct_4B.pack(*self.mask))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      self.values = _struct_4B.unpack(str[start:end])
      self.values = map(bool, self.values)
      start = end
      end += 4
      self.mask = _struct_4B.unpack(str[start:end])
      self.mask = map(bool, self.mask)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.values.tostring())
      buff.write(self.mask.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      self.values = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=4)
      self.values = map(bool, self.values)
      start = end
      end += 4
      self.mask = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=4)
      self.mask = map(bool, self.mask)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
