"""autogenerated by genpy from kobuki_msgs/KeyboardInput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KeyboardInput(genpy.Message):
  _md5sum = "9288b95cb32b48719d84d696be253401"
  _type = "kobuki_msgs/KeyboardInput"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# KEYBOARD INPUT
# 
# Keycodes to be transferred for remote teleops.

uint8  KeyCode_Right    = 67     # 0x43
uint8  KeyCode_Left     = 68     # 0x44
uint8  KeyCode_Up       = 65     # 0x41
uint8  KeyCode_Down     = 66     # 0x42
uint8  KeyCode_Space    = 32     # 0x20
uint8  KeyCode_Enable   = 101    # 0x65, 'e'
uint8  KeyCode_Disable  = 100    # 0x64, 'd'

uint8 pressedKey
"""
  # Pseudo-constants
  KeyCode_Right = 67
  KeyCode_Left = 68
  KeyCode_Up = 65
  KeyCode_Down = 66
  KeyCode_Space = 32
  KeyCode_Enable = 101
  KeyCode_Disable = 100

  __slots__ = ['pressedKey']
  _slot_types = ['uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pressedKey

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KeyboardInput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pressedKey is None:
        self.pressedKey = 0
    else:
      self.pressedKey = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.pressedKey))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.pressedKey,) = _struct_B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.pressedKey))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.pressedKey,) = _struct_B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
