"""autogenerated by genpy from kobuki_msgs/VersionInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VersionInfo(genpy.Message):
  _md5sum = "adb07428ccdeb5dcaa56f5ef3160a76c"
  _type = "kobuki_msgs/VersionInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Contains version info for the kobuki platform.
# Useful for introspection

uint16 firmware
uint16 hardware
uint32 software
uint32[] udid


"""
  __slots__ = ['firmware','hardware','software','udid']
  _slot_types = ['uint16','uint16','uint32','uint32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       firmware,hardware,software,udid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VersionInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.firmware is None:
        self.firmware = 0
      if self.hardware is None:
        self.hardware = 0
      if self.software is None:
        self.software = 0
      if self.udid is None:
        self.udid = []
    else:
      self.firmware = 0
      self.hardware = 0
      self.software = 0
      self.udid = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2HI.pack(_x.firmware, _x.hardware, _x.software))
      length = len(self.udid)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.udid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.firmware, _x.hardware, _x.software,) = _struct_2HI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.udid = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2HI.pack(_x.firmware, _x.hardware, _x.software))
      length = len(self.udid)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.udid.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.firmware, _x.hardware, _x.software,) = _struct_2HI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.udid = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2HI = struct.Struct("<2HI")
