(cl:in-package kobuki_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_STAMP-VAL
          TIME_STAMP
          BUMPER-VAL
          BUMPER
          WHEEL_DROP-VAL
          WHEEL_DROP
          CLIFF-VAL
          CLIFF
          LEFT_ENCODER-VAL
          LEFT_ENCODER
          RIGHT_ENCODER-VAL
          RIGHT_ENCODER
          LEFT_PWM-VAL
          LEFT_PWM
          RIGHT_PWM-VAL
          RIGHT_PWM
          BUTTONS-VAL
          BUTTONS
          CHARGER-VAL
          CHARGER
          BATTERY-VAL
          BATTERY
          BOTTOM-VAL
          BOTTOM
          CURRENT-VAL
          CURRENT
          OVER_CURRENT-VAL
          OVER_CURRENT
          DIGITAL_INPUT-VAL
          DIGITAL_INPUT
          ANALOG_INPUT-VAL
          ANALOG_INPUT
))