; Auto-generated. Do not edit!


(cl:in-package kobuki_msgs-msg)


;//! \htmlinclude PowerSystemEvent.msg.html

(cl:defclass <PowerSystemEvent> (roslisp-msg-protocol:ros-message)
  ((event
    :reader event
    :initarg :event
    :type cl:fixnum
    :initform 0))
)

(cl:defclass PowerSystemEvent (<PowerSystemEvent>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PowerSystemEvent>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PowerSystemEvent)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kobuki_msgs-msg:<PowerSystemEvent> is deprecated: use kobuki_msgs-msg:PowerSystemEvent instead.")))

(cl:ensure-generic-function 'event-val :lambda-list '(m))
(cl:defmethod event-val ((m <PowerSystemEvent>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kobuki_msgs-msg:event-val is deprecated.  Use kobuki_msgs-msg:event instead.")
  (event m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<PowerSystemEvent>)))
    "Constants for message type '<PowerSystemEvent>"
  '((:UNPLUGGED . 0)
    (:PLUGGED_TO_ADAPTER . 1)
    (:PLUGGED_TO_DOCKBASE . 2)
    (:CHARGE_COMPLETED . 3)
    (:BATTERY_LOW . 4)
    (:BATTERY_CRITICAL . 5))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'PowerSystemEvent)))
    "Constants for message type 'PowerSystemEvent"
  '((:UNPLUGGED . 0)
    (:PLUGGED_TO_ADAPTER . 1)
    (:PLUGGED_TO_DOCKBASE . 2)
    (:CHARGE_COMPLETED . 3)
    (:BATTERY_LOW . 4)
    (:BATTERY_CRITICAL . 5))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PowerSystemEvent>) ostream)
  "Serializes a message object of type '<PowerSystemEvent>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'event)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PowerSystemEvent>) istream)
  "Deserializes a message object of type '<PowerSystemEvent>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'event)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PowerSystemEvent>)))
  "Returns string type for a message object of type '<PowerSystemEvent>"
  "kobuki_msgs/PowerSystemEvent")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PowerSystemEvent)))
  "Returns string type for a message object of type 'PowerSystemEvent"
  "kobuki_msgs/PowerSystemEvent")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PowerSystemEvent>)))
  "Returns md5sum for a message object of type '<PowerSystemEvent>"
  "f6464657d6c911b00c7bc7b43a154bf8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PowerSystemEvent)))
  "Returns md5sum for a message object of type 'PowerSystemEvent"
  "f6464657d6c911b00c7bc7b43a154bf8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PowerSystemEvent>)))
  "Returns full string definition for message of type '<PowerSystemEvent>"
  (cl:format cl:nil "# Power system events~%# This message is generated by important changes in the power system:~%#  - plug/unplug to the docking base or adapter~%#  - transitions to low/critical battery levels~%#  - battery charge completed~%~%uint8 UNPLUGGED           = 0~%uint8 PLUGGED_TO_ADAPTER  = 1~%uint8 PLUGGED_TO_DOCKBASE = 2~%uint8 CHARGE_COMPLETED    = 3~%uint8 BATTERY_LOW         = 4~%uint8 BATTERY_CRITICAL    = 5~%~%uint8 event~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PowerSystemEvent)))
  "Returns full string definition for message of type 'PowerSystemEvent"
  (cl:format cl:nil "# Power system events~%# This message is generated by important changes in the power system:~%#  - plug/unplug to the docking base or adapter~%#  - transitions to low/critical battery levels~%#  - battery charge completed~%~%uint8 UNPLUGGED           = 0~%uint8 PLUGGED_TO_ADAPTER  = 1~%uint8 PLUGGED_TO_DOCKBASE = 2~%uint8 CHARGE_COMPLETED    = 3~%uint8 BATTERY_LOW         = 4~%uint8 BATTERY_CRITICAL    = 5~%~%uint8 event~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PowerSystemEvent>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PowerSystemEvent>))
  "Converts a ROS message object to a list"
  (cl:list 'PowerSystemEvent
    (cl:cons ':event (event msg))
))
