#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the kobuki usb connection as /dev/kobuki."
echo ""

sudo cp `rospack find kobuki_ftdi`/57-kobuki.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart

