#include $(shell rospack find mk)/cmake.mk

# Transfer this to the CMakeLists.txt later.

all:
	pyrcc4 -o src/kobuki_qtestsuite/resources/common.py src/kobuki_qtestsuite/resources/common.qrc
	pyrcc4 -o src/kobuki_qtestsuite/resources/climbing.py src/kobuki_qtestsuite/resources/climbing.qrc
