#!/bin/bash
# installs and builds kobuki's software bundle

sudo apt-get install -y ros-electric-turtlebot-robot ros-electric-dynamixel-motor ros-electric-laser-drivers
rm -rf ${WORKSPACE}/kobuki_workspace
rosinstall ${WORKSPACE}/kobuki_workspace https://raw.github.com/yujinrobot/kobuki/master/kobuki_unstable_jenkins.rosinstall
source ${WORKSPACE}/kobuki_workspace/setup.bash
export ROS_PARALLEL_JOBS="-l5"
export ROS_HOME=${WORKSPACE}
rosmake kobuki_bringup
rosmake --target=test kobuki_bringup
