/* Auto-generated by genmsg_cpp for file /opt/jihoonl/kobuki/kobuki_msgs/msg/BumperEvent.msg */
#ifndef KOBUKI_MSGS_MESSAGE_BUMPEREVENT_H
#define KOBUKI_MSGS_MESSAGE_BUMPEREVENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kobuki_msgs
{
template <class ContainerAllocator>
struct BumperEvent_ {
  typedef BumperEvent_<ContainerAllocator> Type;

  BumperEvent_()
  : state(0)
  , bumper(0)
  {
  }

  BumperEvent_(const ContainerAllocator& _alloc)
  : state(0)
  , bumper(0)
  {
  }

  typedef uint8_t _state_type;
  uint8_t state;

  typedef uint8_t _bumper_type;
  uint8_t bumper;

  enum { LEFT = 0 };
  enum { CENTER = 1 };
  enum { RIGHT = 2 };
  enum { RELEASED = 0 };
  enum { PRESSED = 1 };

  typedef boost::shared_ptr< ::kobuki_msgs::BumperEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_msgs::BumperEvent_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BumperEvent
typedef  ::kobuki_msgs::BumperEvent_<std::allocator<void> > BumperEvent;

typedef boost::shared_ptr< ::kobuki_msgs::BumperEvent> BumperEventPtr;
typedef boost::shared_ptr< ::kobuki_msgs::BumperEvent const> BumperEventConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kobuki_msgs::BumperEvent_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kobuki_msgs::BumperEvent_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kobuki_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::BumperEvent_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::BumperEvent_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kobuki_msgs::BumperEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "34e76e5dbfb320b33636dacfb99fb3e2";
  }

  static const char* value(const  ::kobuki_msgs::BumperEvent_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x34e76e5dbfb320b3ULL;
  static const uint64_t static_value2 = 0x3636dacfb99fb3e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_msgs::BumperEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kobuki_msgs/BumperEvent";
  }

  static const char* value(const  ::kobuki_msgs::BumperEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kobuki_msgs::BumperEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Provides a button event\n\
# This message is generated whenever a button is pressed or released\n\
\n\
uint8 LEFT = 0\n\
uint8 CENTER = 1\n\
uint8 RIGHT = 2\n\
\n\
uint8 RELEASED = 0\n\
uint8 PRESSED  = 1\n\
\n\
uint8 state\n\
uint8 bumper\n\
\n\
";
  }

  static const char* value(const  ::kobuki_msgs::BumperEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kobuki_msgs::BumperEvent_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kobuki_msgs::BumperEvent_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
    stream.next(m.bumper);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BumperEvent_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_msgs::BumperEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kobuki_msgs::BumperEvent_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "bumper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bumper);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOBUKI_MSGS_MESSAGE_BUMPEREVENT_H

