/* Auto-generated by genmsg_cpp for file /opt/jihoonl/kobuki/kobuki_msgs/msg/ButtonEvent.msg */
#ifndef KOBUKI_MSGS_MESSAGE_BUTTONEVENT_H
#define KOBUKI_MSGS_MESSAGE_BUTTONEVENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kobuki_msgs
{
template <class ContainerAllocator>
struct ButtonEvent_ {
  typedef ButtonEvent_<ContainerAllocator> Type;

  ButtonEvent_()
  : state(0)
  , button(0)
  {
  }

  ButtonEvent_(const ContainerAllocator& _alloc)
  : state(0)
  , button(0)
  {
  }

  typedef uint8_t _state_type;
  uint8_t state;

  typedef uint8_t _button_type;
  uint8_t button;

  enum { Button0 = 0 };
  enum { Button1 = 1 };
  enum { Button2 = 2 };
  enum { RELEASED = 0 };
  enum { PRESSED = 1 };

  typedef boost::shared_ptr< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_msgs::ButtonEvent_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ButtonEvent
typedef  ::kobuki_msgs::ButtonEvent_<std::allocator<void> > ButtonEvent;

typedef boost::shared_ptr< ::kobuki_msgs::ButtonEvent> ButtonEventPtr;
typedef boost::shared_ptr< ::kobuki_msgs::ButtonEvent const> ButtonEventConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kobuki_msgs::ButtonEvent_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kobuki_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::ButtonEvent_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "627fdd6fd6471539e5190c0e4fadb9c2";
  }

  static const char* value(const  ::kobuki_msgs::ButtonEvent_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x627fdd6fd6471539ULL;
  static const uint64_t static_value2 = 0xe5190c0e4fadb9c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kobuki_msgs/ButtonEvent";
  }

  static const char* value(const  ::kobuki_msgs::ButtonEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Provides a button event\n\
# This message is generated whenever a button is pressed or released\n\
\n\
uint8 Button0 = 0\n\
uint8 Button1 = 1\n\
uint8 Button2 = 2\n\
\n\
uint8 RELEASED = 0\n\
uint8 PRESSED  = 1\n\
\n\
uint8 state\n\
uint8 button\n\
\n\
";
  }

  static const char* value(const  ::kobuki_msgs::ButtonEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
    stream.next(m.button);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ButtonEvent_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_msgs::ButtonEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kobuki_msgs::ButtonEvent_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOBUKI_MSGS_MESSAGE_BUTTONEVENT_H

