/* Auto-generated by genmsg_cpp for file /opt/jihoonl/kobuki/kobuki_msgs/msg/CliffEvent.msg */
#ifndef KOBUKI_MSGS_MESSAGE_CLIFFEVENT_H
#define KOBUKI_MSGS_MESSAGE_CLIFFEVENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kobuki_msgs
{
template <class ContainerAllocator>
struct CliffEvent_ {
  typedef CliffEvent_<ContainerAllocator> Type;

  CliffEvent_()
  : state(0)
  , sensor(0)
  , bottom(0)
  {
  }

  CliffEvent_(const ContainerAllocator& _alloc)
  : state(0)
  , sensor(0)
  , bottom(0)
  {
  }

  typedef uint8_t _state_type;
  uint8_t state;

  typedef uint8_t _sensor_type;
  uint8_t sensor;

  typedef uint16_t _bottom_type;
  uint16_t bottom;

  enum { LEFT = 0 };
  enum { CENTER = 1 };
  enum { RIGHT = 2 };
  enum { FLOOR = 0 };
  enum { CLIFF = 1 };

  typedef boost::shared_ptr< ::kobuki_msgs::CliffEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_msgs::CliffEvent_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CliffEvent
typedef  ::kobuki_msgs::CliffEvent_<std::allocator<void> > CliffEvent;

typedef boost::shared_ptr< ::kobuki_msgs::CliffEvent> CliffEventPtr;
typedef boost::shared_ptr< ::kobuki_msgs::CliffEvent const> CliffEventConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kobuki_msgs::CliffEvent_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kobuki_msgs::CliffEvent_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kobuki_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::CliffEvent_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::CliffEvent_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kobuki_msgs::CliffEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "768947926ed252fd64a5711160ff3884";
  }

  static const char* value(const  ::kobuki_msgs::CliffEvent_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x768947926ed252fdULL;
  static const uint64_t static_value2 = 0x64a5711160ff3884ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_msgs::CliffEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kobuki_msgs/CliffEvent";
  }

  static const char* value(const  ::kobuki_msgs::CliffEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kobuki_msgs::CliffEvent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Provides a cliff sensor event\n\
# This message is generated whenever the robot approaches or moves away from a cliff\n\
\n\
uint8 LEFT   = 0\n\
uint8 CENTER = 1\n\
uint8 RIGHT  = 2\n\
\n\
uint8 FLOOR = 0\n\
uint8 CLIFF = 1\n\
\n\
uint8  state\n\
uint8  sensor\n\
uint16 bottom\n\
";
  }

  static const char* value(const  ::kobuki_msgs::CliffEvent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kobuki_msgs::CliffEvent_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kobuki_msgs::CliffEvent_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
    stream.next(m.sensor);
    stream.next(m.bottom);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CliffEvent_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_msgs::CliffEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kobuki_msgs::CliffEvent_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor);
    s << indent << "bottom: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.bottom);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOBUKI_MSGS_MESSAGE_CLIFFEVENT_H

