/* Auto-generated by genmsg_cpp for file /opt/jihoonl/kobuki/kobuki_msgs/msg/DockInfraRed.msg */
#ifndef KOBUKI_MSGS_MESSAGE_DOCKINFRARED_H
#define KOBUKI_MSGS_MESSAGE_DOCKINFRARED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kobuki_msgs
{
template <class ContainerAllocator>
struct DockInfraRed_ {
  typedef DockInfraRed_<ContainerAllocator> Type;

  DockInfraRed_()
  : header()
  , data()
  {
  }

  DockInfraRed_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , data(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  data;

  enum { NEAR_LEFT = 1 };
  enum { NEAR_CENTER = 2 };
  enum { NEAR_RIGHT = 4 };
  enum { FAR_LEFT = 8 };
  enum { FAR_CENTER = 16 };
  enum { FAR_RIGHT = 32 };

  typedef boost::shared_ptr< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_msgs::DockInfraRed_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DockInfraRed
typedef  ::kobuki_msgs::DockInfraRed_<std::allocator<void> > DockInfraRed;

typedef boost::shared_ptr< ::kobuki_msgs::DockInfraRed> DockInfraRedPtr;
typedef boost::shared_ptr< ::kobuki_msgs::DockInfraRed const> DockInfraRedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kobuki_msgs::DockInfraRed_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kobuki_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::DockInfraRed_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4247d91ea10269fb062c53396d016a2c";
  }

  static const char* value(const  ::kobuki_msgs::DockInfraRed_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4247d91ea10269fbULL;
  static const uint64_t static_value2 = 0x062c53396d016a2cULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kobuki_msgs/DockInfraRed";
  }

  static const char* value(const  ::kobuki_msgs::DockInfraRed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 NEAR_LEFT   =  1\n\
uint8 NEAR_CENTER =  2\n\
uint8 NEAR_RIGHT  =  4\n\
uint8 FAR_LEFT    =  8\n\
uint8 FAR_CENTER  = 16\n\
uint8 FAR_RIGHT   = 32\n\
\n\
Header header\n\
uint8[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kobuki_msgs::DockInfraRed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kobuki_msgs::DockInfraRed_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DockInfraRed_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_msgs::DockInfraRed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kobuki_msgs::DockInfraRed_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOBUKI_MSGS_MESSAGE_DOCKINFRARED_H

