/* Auto-generated by genmsg_cpp for file /opt/jihoonl/kobuki/kobuki_msgs/msg/Led.msg */
#ifndef KOBUKI_MSGS_MESSAGE_LED_H
#define KOBUKI_MSGS_MESSAGE_LED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kobuki_msgs
{
template <class ContainerAllocator>
struct Led_ {
  typedef Led_<ContainerAllocator> Type;

  Led_()
  : value(0)
  {
  }

  Led_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef uint8_t _value_type;
  uint8_t value;

  enum { BLACK = 0 };
  enum { GREEN = 1 };
  enum { ORANGE = 2 };
  enum { RED = 3 };

  typedef boost::shared_ptr< ::kobuki_msgs::Led_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_msgs::Led_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Led
typedef  ::kobuki_msgs::Led_<std::allocator<void> > Led;

typedef boost::shared_ptr< ::kobuki_msgs::Led> LedPtr;
typedef boost::shared_ptr< ::kobuki_msgs::Led const> LedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kobuki_msgs::Led_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kobuki_msgs::Led_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kobuki_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::Led_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::Led_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kobuki_msgs::Led_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4391183b0cf05f8f25d04220401b9f43";
  }

  static const char* value(const  ::kobuki_msgs::Led_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4391183b0cf05f8fULL;
  static const uint64_t static_value2 = 0x25d04220401b9f43ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_msgs::Led_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kobuki_msgs/Led";
  }

  static const char* value(const  ::kobuki_msgs::Led_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kobuki_msgs::Led_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Sends a command for controlling the a LED.\n\
# \n\
# Typically the first LED is always reserved to denote\n\
# the state - the remainder will be controllable. \n\
\n\
uint8 BLACK   = 0\n\
uint8 GREEN   = 1\n\
uint8 ORANGE  = 2\n\
uint8 RED     = 3\n\
\n\
# For kobuki there are only two controllable LED's.\n\
uint8 value\n\
\n\
";
  }

  static const char* value(const  ::kobuki_msgs::Led_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kobuki_msgs::Led_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kobuki_msgs::Led_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Led_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_msgs::Led_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kobuki_msgs::Led_<ContainerAllocator> & v) 
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOBUKI_MSGS_MESSAGE_LED_H

