/* Auto-generated by genmsg_cpp for file /opt/jihoonl/kobuki/kobuki_msgs/msg/Sound.msg */
#ifndef KOBUKI_MSGS_MESSAGE_SOUND_H
#define KOBUKI_MSGS_MESSAGE_SOUND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kobuki_msgs
{
template <class ContainerAllocator>
struct Sound_ {
  typedef Sound_<ContainerAllocator> Type;

  Sound_()
  : value(0)
  {
  }

  Sound_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef uint8_t _value_type;
  uint8_t value;

  enum { ON = 0 };
  enum { OFF = 1 };
  enum { RECHARGE = 2 };
  enum { BUTTON = 3 };
  enum { ERROR = 4 };
  enum { CLEANINGSTART = 5 };
  enum { CLEANINGEND = 6 };

  typedef boost::shared_ptr< ::kobuki_msgs::Sound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kobuki_msgs::Sound_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Sound
typedef  ::kobuki_msgs::Sound_<std::allocator<void> > Sound;

typedef boost::shared_ptr< ::kobuki_msgs::Sound> SoundPtr;
typedef boost::shared_ptr< ::kobuki_msgs::Sound const> SoundConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kobuki_msgs::Sound_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kobuki_msgs::Sound_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kobuki_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::Sound_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kobuki_msgs::Sound_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kobuki_msgs::Sound_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dfeab0daae67749c426c1db741a4f420";
  }

  static const char* value(const  ::kobuki_msgs::Sound_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdfeab0daae67749cULL;
  static const uint64_t static_value2 = 0x426c1db741a4f420ULL;
};

template<class ContainerAllocator>
struct DataType< ::kobuki_msgs::Sound_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kobuki_msgs/Sound";
  }

  static const char* value(const  ::kobuki_msgs::Sound_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kobuki_msgs::Sound_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Sends a command for playing sounds.\n\
# The available sound sequences:\n\
# 0 - turn on\n\
# 1 - turn off\n\
# 2 - recharge start\n\
# 3 - press button,\n\
# 4 - error sound\n\
# 5 - start cleaning\n\
# 6 - cleaning end\n\
\n\
uint8 ON            = 0\n\
uint8 OFF           = 1\n\
uint8 RECHARGE      = 2\n\
uint8 BUTTON        = 3\n\
uint8 ERROR         = 4\n\
uint8 CLEANINGSTART = 5\n\
uint8 CLEANINGEND   = 6\n\
\n\
uint8 value\n\
";
  }

  static const char* value(const  ::kobuki_msgs::Sound_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kobuki_msgs::Sound_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kobuki_msgs::Sound_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Sound_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kobuki_msgs::Sound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kobuki_msgs::Sound_<ContainerAllocator> & v) 
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KOBUKI_MSGS_MESSAGE_SOUND_H

