#!/bin/bash
# installs and builds kobuki's software bundle

sudo apt-get install -y ros-fuerte-desktop-full
sudo apt-get install -y ros-fuerte-turtlebot ros-fuerte-turtlebot-apps ros-fuerte-control
sudo apt-get install -y ros-fuerte-warehousewg
sudo apt-get install -y ros-fuerte-turtlebot-viz ros-fuerte-simulators
sudo apt-get install -y libavahi-core-dev
rm -rf ${WORKSPACE}/kobuki_workspace
rosinstall ${WORKSPACE}/kobuki_workspace https://raw.github.com/yujinrobot/kobuki/master/kobuki_unstable.rosinstall
source ${WORKSPACE}/kobuki_workspace/setup.bash
export ROS_PARALLEL_JOBS="-l5"
export ROS_HOME=${WORKSPACE}
rosdep install kobuki_utilities
rosdep install kobuki_gazebo
rosmake --pre-clean kobuki_utilities
rosmake --pre-clean kobuki_gazebo
rosmake --target=test kobuki_utilities
